name: vc-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.13
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - curl=7.78.0
  - gsl=2.6
  - htslib=1.13
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libcxx=10.0.0
  - libdeflate=1.7
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.17
  - libssh2=1.9.0
  - llvm-openmp=12.0.1
  - ncurses=6.2
  - openssl=1.1.1k
  - perl=5.26.2
  - pip=21.0.1
  - python=3.7.11
  - python_abi=3.7
  - readline=8.1
  - samtools=1.13
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
prefix: /Users/rbiswas/miniconda3/envs/vc-env
